import React, { useState } from 'react';
import { Copy, Download, FileText, Check, Sparkles, BookOpen, AlertCircle, FileCheck } from 'lucide-react';
import { AINotes } from '../../types';

interface AINotesTabProps {
  notes: AINotes;
  videoTitle: string;
}

export default function AINotesTab({ notes, videoTitle }: AINotesTabProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyAll = () => {
    const formattedText = `# ${videoTitle}\n\n## Executive Summary\n${notes.summary}\n\n## Introduction\n${notes.introduction}\n\n## Key Concepts\n${notes.keyConcepts.map((k) => `- **${k.concept}**: ${k.explanation}`).join('\n')}\n\n## Key Takeaways\n${notes.keyTakeaways.map((t) => `- ${t}`).join('\n')}`;
    navigator.clipboard.writeText(formattedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const content = `# ${videoTitle}\n\n> Generated by AI YouTube Learning Assistant\n\n## Summary\n${notes.summary}\n\n## Introduction\n${notes.introduction}\n\n## Key Concepts\n${notes.keyConcepts.map((k) => `### ${k.concept}\n${k.explanation}`).join('\n\n')}\n\n## Detailed Breakdown\n${notes.detailedSections.map((s) => `### ${s.title}\n${s.content}\n${s.bulletPoints ? s.bulletPoints.map((b) => `- ${b}`).join('\n') : ''}`).join('\n\n')}\n\n## Key Takeaways\n${notes.keyTakeaways.map((t) => `- ${t}`).join('\n')}`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${videoTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notes.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6 animate-in fade-in">
      {/* Header Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <div>
          <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-indigo-600" />
            AI Structured Study Notes
          </h3>
          <p className="text-xs text-slate-500 mt-0.5">Comprehensive conceptual breakdown generated from transcript</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 rounded-xl border border-slate-200 bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition-colors cursor-pointer"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied' : 'Copy All'}</span>
          </button>
          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 rounded-xl bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-indigo-500 transition-colors cursor-pointer shadow-sm"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download .MD</span>
          </button>
        </div>
      </div>

      {/* Summary Banner */}
      <div className="rounded-2xl border border-indigo-200 bg-indigo-50/70 p-5 shadow-sm">
        <h4 className="text-xs font-bold uppercase tracking-wider text-indigo-700">Executive Summary</h4>
        <p className="mt-2 text-sm text-slate-800 leading-relaxed font-normal">{notes.summary}</p>
      </div>

      {/* Introduction */}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
          <BookOpen className="h-4 w-4 text-indigo-600" />
          Introduction & Core Objectives
        </h4>
        <p className="text-xs text-slate-600 leading-relaxed">{notes.introduction}</p>
      </div>

      {/* Key Concepts Grid */}
      <div>
        <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">Key Concepts</h4>
        <div className="grid gap-3 sm:grid-cols-2">
          {notes.keyConcepts.map((kc, idx) => (
            <div key={idx} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm hover:border-indigo-300 transition-all">
              <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider">Concept {idx + 1}</span>
              <h5 className="text-sm font-bold text-slate-900 mt-1">{kc.concept}</h5>
              <p className="text-xs text-slate-600 mt-2 leading-relaxed">{kc.explanation}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Detailed Breakdown Sections */}
      {notes.detailedSections.map((sec, idx) => (
        <div key={idx} className="rounded-2xl border border-slate-200 bg-white p-5 space-y-3 shadow-sm">
          <h4 className="text-sm font-bold text-slate-900">{sec.title}</h4>
          <p className="text-xs text-slate-600 leading-relaxed">{sec.content}</p>
          {sec.bulletPoints && sec.bulletPoints.length > 0 && (
            <ul className="space-y-1.5 pl-2 pt-1">
              {sec.bulletPoints.map((bp, bIdx) => (
                <li key={bIdx} className="flex items-start gap-2 text-xs text-slate-600">
                  <span className="h-1.5 w-1.5 rounded-full bg-indigo-600 mt-1.5 shrink-0" />
                  <span>{bp}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      ))}

      {/* Important Definitions */}
      {notes.importantDefinitions && notes.importantDefinitions.length > 0 && (
        <div className="rounded-2xl border border-slate-200 bg-white p-5 space-y-3 shadow-sm">
          <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <FileCheck className="h-4 w-4 text-emerald-600" />
            Important Terminology & Definitions
          </h4>
          <div className="grid gap-2 sm:grid-cols-2">
            {notes.importantDefinitions.map((def, idx) => (
              <div key={idx} className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-3">
                <span className="text-xs font-bold text-emerald-900">{def.term}</span>
                <p className="text-xs text-slate-600 mt-1">{def.definition}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Common Mistakes & Takeaways */}
      <div className="grid gap-4 sm:grid-cols-2">
        {notes.commonMistakes && notes.commonMistakes.length > 0 && (
          <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 space-y-2 shadow-sm">
            <h4 className="text-xs font-bold text-amber-900 flex items-center gap-1.5">
              <AlertCircle className="h-4 w-4 text-amber-600" />
              Common Mistakes to Avoid
            </h4>
            <ul className="space-y-1.5">
              {notes.commonMistakes.map((m, idx) => (
                <li key={idx} className="text-xs text-amber-900/90 leading-snug flex items-start gap-2">
                  <span className="text-amber-600 shrink-0">•</span>
                  <span>{m}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {notes.keyTakeaways && notes.keyTakeaways.length > 0 && (
          <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 space-y-2 shadow-sm">
            <h4 className="text-xs font-bold text-indigo-900 flex items-center gap-1.5">
              <FileText className="h-4 w-4 text-indigo-600" />
              Key Takeaways
            </h4>
            <ul className="space-y-1.5">
              {notes.keyTakeaways.map((t, idx) => (
                <li key={idx} className="text-xs text-indigo-900/90 leading-snug flex items-start gap-2">
                  <span className="text-indigo-600 shrink-0">•</span>
                  <span>{t}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
